apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-nginx
  labels:
    team: finance
    version: 1.1.0
    environment: prod
  annotations:
    description: A product is the item offered for sale
spec:
  selector:
    matchLabels:
      name: daemon-nginx
  template:
    metadata:
      name: daemon-nginx
      labels:
        name: daemon-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3