apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    team: finance
    version: 1.1.0
    environment: prod
  annotations:
    description: A product is the item offered for sale
spec:
  containers:
    - name: nginx-pod
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /404
          port: 80
        initialDelaySeconds: 1
        periodSeconds: 10
        timeoutSeconds: 3
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /404
          port: 80
        initialDelaySeconds: 1
        periodSeconds: 10
        timeoutSeconds: 3
        successThreshold: 1
        failureThreshold: 3
      startupProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 1
        periodSeconds: 10
        timeoutSeconds: 3
        successThreshold: 1
        failureThreshold: 3