apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label
  labels:
    team: finance
    version: 1.1.0
    environment: prod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80