apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  labels:
    label-key1: label-value1
  annotations:
    annotation-key1: annotation-value
    annotation-key2: very long annotation value, ......
spec:
  containers:
    - name: container-name
      image: image-name
      ports:
        - containerPort: 80

#create => kubectl create -f [pod-name].yaml
#list view => kubectl get pod --show-labels
#change annotation =>
#  - kubectl annotate pod [pod-name] [key]=[value]
#  - kubectl annotate pod [pod-name] [key]=[value] --overwrite