apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  containers:
    - name: container-name
      image: image-name
      ports:
        - containerPort: 80


#create => kubectl create -f pod-name.yaml
#list view => kubectl get pod | kubectl get pod -o wide
#detail list => kubectl describe pod [pod-name]
#port forward => kubectl port-forward [pod-name] [access-port]:[pod-port] => exam : kubectl port-forward nginx 8888:80